<?php

namespace App\Http\Controllers;

class AdminOutsourcingController extends Controller
{
    public function dashboard()
    {
        $datas = [
            [
                'no' => 1,
                'nama' => 'Rizky Darmawan',
                'inisial' => 'RD',
                'perusahaan' => 'PT. Chemistry Jaya',
                'posisi' => 'Operator',
                'warna' => 'bg-green-600',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],

            [
                'no' => 2,
                'nama' => 'Siti Aminah',
                'inisial' => 'SA',
                'perusahaan' => 'PT. TechSolution',
                'posisi' => 'Teknisi',
                'warna' => 'bg-emerald-600',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                ],
            ],

            [
                'no' => 3,
                'nama' => 'Budi Santoso',
                'inisial' => 'BS',
                'perusahaan' => 'PT. GlobalMaju',
                'posisi' => 'Helper',
                'warna' => 'bg-blue-500',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],
            [
                'no' => 4,
                'nama' => 'Andi Pratama',
                'inisial' => 'AP',
                'perusahaan' => 'PT. Sinar Abadi',
                'posisi' => 'Operator',
                'warna' => 'bg-indigo-600',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],

            [
                'no' => 5,
                'nama' => 'Dewi Lestari',
                'inisial' => 'DL',
                'perusahaan' => 'PT. Nusantara Tech',
                'posisi' => 'Admin',
                'warna' => 'bg-pink-500',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],
            [
                'no' => 6,
                'nama' => 'Rian Saputra',
                'inisial' => 'RS',
                'perusahaan' => 'PT. Globalindo',
                'posisi' => 'Driver',
                'warna' => 'bg-orange-500',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],

            [
                'no' => 7,
                'nama' => 'Maya Sari',
                'inisial' => 'MS',
                'perusahaan' => 'PT. Mitra Jaya',
                'posisi' => 'HR',
                'warna' => 'bg-teal-500',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],

            [
                'no' => 8,
                'nama' => 'Fajar Nugroho',
                'inisial' => 'FN',
                'perusahaan' => 'PT. Karya Mandiri',
                'posisi' => 'Security',
                'warna' => 'bg-gray-600',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],

            [
                'no' => 9,
                'nama' => 'Tika Ramadhani',
                'inisial' => 'TR',
                'perusahaan' => 'PT. Sumber Rejeki',
                'posisi' => 'Admin',
                'warna' => 'bg-fuchsia-600',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],

            [
                'no' => 10,
                'nama' => 'Yoga Prasetyo',
                'inisial' => 'YP',
                'perusahaan' => 'PT. Mega Industri',
                'posisi' => 'Operator',
                'warna' => 'bg-cyan-600',
                'absens' => [
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'S', 'warna' => 'bg-yellow-100 text-yellow-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'I', 'warna' => 'bg-blue-100 text-blue-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'A', 'warna' => 'bg-red-100 text-red-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => 'L', 'warna' => 'bg-purple-100 text-purple-700'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                    ['value' => '-', 'warna' => 'text-gray-300'],
                    ['value' => 'H', 'warna' => 'bg-green-100 text-green-700'],
                ],
            ],
        ];

        return view('adminOutsourcing.dashboard', compact('datas'));
    }

    
}
